jerry_server:
    build: .
    dockerfile: ./docker/Dockerfile
    container_name: jerry_framework
    working_dir: /var/www/html
    ports:
        - "80:80"
    volumes:
        - .:/var/www/html
        - ./docker/nginx_log:/var/log/nginx
        - ./docker/php-fpm/php-fpm.log:/var/log/php-fom.log
        - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - mysql

mysql:
  image: mysql:5.0
  container_name: jerry_mysql
  ports:
    - "3308:3306"
  volumes:
    - ./docker/mysql:/var/lib/mysql
  enviroment:  
    MYSQL_ROOT_PASSWORD: password